trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self  # Check out the repository to access the config.json file

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Specify the Node.js version required
    displayName: 'Install Node.js'

  - script: |
      # Install jq for JSON parsing
      sudo apt-get install -y jq

      # Read the API_KEY, OID, and PID from config.json
      API_KEY=$(jq -r '.API_KEY' config.json)
      OID=$(jq -r '.OID' config.json)
      PID=$(jq -r '.PID' config.json)

      # Print masked values (they will be masked in logs automatically)
      echo "OID: ***"
      echo "PID: ***"
      echo "API Key: ***"

      # Execute the API request using curl and payload.json
      curl -X POST "https://cloudapi.cloud.couchbase.com/v4/organizations/${OID}/projects/${PID}/clusters" \
        -H "Authorization: Bearer ${API_KEY}" \
        -H "Content-Type: application/json" \
        -d @payload.json  # Assuming payload.json is in the same directory
    displayName: 'Create Couchbase Cluster'
