trigger:
  - main
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
  - checkout: self

  # Using Azure CLI Task
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AzureServiceConnection'  # Replace with your actual service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Load API Key, OID, and PID from GitHub Secrets
        API_KEY=${{ secrets.API_KEY }}
        OID=${{ secrets.OID }}
        PID=${{ secrets.PID }}
        
        # Validate that secrets are available (they will be masked in logs)
        echo "OID: ***"
        echo "PID: ***"
        echo "API Key: ***"

        # Execute the API request using curl and payload.json
        curl -X POST "https://cloudapi.cloud.couchbase.com/v4/organizations/${OID}/projects/${PID}/clusters" \
          -H "Authorization: Bearer ${API_KEY}" \
          -H "Content-Type: application/json" \
          -d @payload.json
