trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  API_KEY: $(API_KEY)   # Secure variable defined in the pipeline
  OID: $(OID)           # Organization ID
  PID: $(PID)           # Project ID

steps:
  - checkout: self  # Check out the repository to access the payload.json file

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AzureServiceConnection'  # Replace with your Azure service connection
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Print the variables to validate they're correct
        echo "Organization ID (OID): $(OID)"
        echo "Project ID (PID): $(PID)"
        echo "Masked API Key: ***"  # Masked for security

        # Print the contents of payload.json for debugging purposes
        echo "Payload file contents:"
        cat payload.json

        # Execute the curl request with the loaded payload
        PAYLOAD=$(<payload.json)  # Load payload.json into the variable
        curl -X POST "https://cloudapi.cloud.couchbase.com/v4/organizations/$(OID)/projects/$(PID)/clusters" \
          -H "Authorization: Bearer $(API_KEY)" \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD"

    displayName: 'Create Couchbase Cluster'
